### ISSUE TITLE
[PE-D][Tester C] Command words under `Commands` and `Command Summary` do not match in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W10-1/tp#218] opened 2024-11-08 15:40 UTC
![Screenshot 2024-11-08 at 4.20.43 PM.png](https://raw.githubusercontent.com/wang-h-z/ped/main/files/826ba369-c534-4fa6-863c-836df33d87e0.png)

In `Commands`, this feature utilises `listattn` command word.

An update to the UG will fix this issue.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: wang-h-z/ped#2

**Comment by NicholasT1** [comment] 2024-11-09 03:42
Closed as duplicate of #254

**Closed by NicholasT1** 2024-11-09 03:42 UTC
